name: Build and Release APK

on:
  push:
    tags:
      - 'v*' # Automatically triggers whenever you push a tag like v2.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make Gradle executable
      run: chmod +x gradlew

    - name: Build Release APK with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
